# numpy
numpyはPythonによるあらゆる数値計算を可能にするライブラリです。

多次元配置や行列を簡単に操作できるため、機械学習のみならず、あらゆる分野で活用されています。

In [1]:
import numpy as np

# 基本的な配列の生成
配列の生成には、np.arrayメソッドを使います。

In [2]:
np.array(1)

array(1)

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

# 形状の確認
配列を操作するようになると、その形状を確認しなければならない状況に多く遭遇します。

その際は、shape属性を参照すると形状を確認できます。

In [5]:
array = np.array([1, 2, 3])
array.shape

(3,)

In [6]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.shape

(3, 2)

# 形状の変換
データ分析の現場では、配列の形状を変換することも多いです。形状の変換には、reshapeメソッドを使います。

特に列ベクトル（列数１の行列）への変換、多次元配列の１次元への変換は必須のテクニックです。

In [7]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
array.reshape(2, 3) #(2, 3)行列へ変換

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.ravel()

array([1, 2, 3, 4, 5, 6])

# 選択と抽出
配列の一部を選択・抽出したい場面は多く存在します。

特に：（スライス）の用法についてはきちんと理解しておくべきでしょう。

In [11]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# １行目を抽出
array[0]

array([1, 2])

In [13]:
# ２行目以降を抽出
array[1:]

array([[3, 4],
       [5, 6]])

In [14]:
# ２行目までを抽出
array[:2]

array([[1, 2],
       [3, 4]])

In [15]:
# １行目の２列目を抽出
array[0, 1]
# array[0][1]

2

## 列ごとの各要素を取り出す機会はかなり多いので、この用法は確実に覚えましょう。

In [16]:
# ２列目を抽出
array[:, 1]

array([2, 4, 6])

# 条件による選択
配列の中から、ある条件を満たす要素のみを取り出したいときや、ある条件を満たす要素を別の値に置き換えたい場合があります。

その際は、whereメソッドなどを使うと便利です。

In [17]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
array > 4

array([[False, False],
       [False, False],
       [ True,  True]])

In [19]:
array[array > 4]

array([5, 6])

ある条件を満たす要素を置き換えるときは、whereメソッドを使うと便利です。

引数の内容は（　条件、　置き換える値、　条件を満たさない要素の値　）です。

In [20]:
X = np.arange(20).reshape(-1, 1)
y = np.random.rand(20)
y = np.where(y < 0.5, 0, 1).reshape(-1, 1)

X[:][y == 1]

array([ 0,  2,  3,  4,  5,  7,  8, 10, 11, 13, 14, 15, 17, 19])

# 配列の結合
複数の配列を結合したいときは、vstackとhstackメソッドを使います。

vstackは縦方向、hstackは横方向にそれぞれ配列を結合します。

In [21]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([[7, 8], [9, 10], [11, 12]])

np.vstack([array_1, array_2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
np.hstack([array_1, array_2])

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

## 形状の異なった配列を同士を連結することはできません。

In [23]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([7, 8, 9, 10, 11, 12])

print(array_1.shape)
print(array_2.shape)

(3, 2)
(6,)


In [24]:
np.stack([array_1, array_2])

ValueError: all input arrays must have the same shape

# 便利な配列生成
## arange
範囲を指定して配列を生成

In [25]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# zeros 
全ての要素が０である配列を生成

In [26]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# zeros_like
指定した配列と同じ形状のゼロ行列を生成

In [27]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.shape)

(3, 2)


In [28]:
np.zeros_like(array)

array([[0, 0],
       [0, 0],
       [0, 0]])

# ones 
全ての要素が１である配列を生成

In [29]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# ones_like
指定した配列と同じ形状の全ての要素が１である配列を生成

In [30]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.shape)

(3, 2)


In [31]:
np.ones_like(array)

array([[1, 1],
       [1, 1],
       [1, 1]])

# eye
単位行列を生成

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# linspace
指定した範囲を等間隔で分割した配列を生成

In [33]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# 乱数の生成
乱数の生成には、主にrandn, rand, randintのいずれか使います。

- randn: 標準正規分布（平均０，分散１）にしたがって乱数を生成
- rand: ０から１までの範囲で乱数を生成
- randint: 指定した範囲の整数をランダムに抽出

乱数を固定するためには、np.random.seed()を指定します。

In [34]:
np.random.seed(0)

In [35]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [36]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [37]:
np.random.randint(0, 100, 10)

array([82, 99, 88, 49, 29, 19, 19, 14, 39, 32])

# 各種演算
配列に対してもあらゆる演算が可能です。

In [38]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([[7, 8], [9, 10], [11, 12]])

### 四則演算

In [39]:
array_1 + array_2

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [40]:
array_1 - array_2

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [41]:
array_1 * array_2

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [42]:
array_1 / array_2

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

### 累乗

In [43]:
array_1 ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [44]:
np.sqrt(array_1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

### 指数関数・対数関数

In [45]:
np.exp(array)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [46]:
np.log1p(array)

array([[0.69314718, 1.09861229],
       [1.38629436, 1.60943791],
       [1.79175947, 1.94591015]])

# 各種統計量
いろいろな統計量を簡単に計算できます。

In [47]:
array = np.random.randint(0, 100, 20)
array

array([65,  9, 57, 32, 31, 74, 23, 35, 75, 55, 28, 34,  0,  0, 36, 53,  5,
       38, 17, 79])

### 合計・平均・分散・標準偏差

In [48]:
np.sum(array)

746

In [49]:
np.mean(array)

37.3

In [50]:
np.var(array)

581.9100000000001

In [51]:
np.std(array)

24.12281078149891

### 最大値・最小値

In [52]:
np.max(array)

79

In [53]:
np.argmax(array)

19

In [54]:
np.min(array)

0

In [55]:
np.argmin(array)

12

# その他
その他のよく使う機能をまとめます。

### データ型を確認する

In [56]:
array = np.random.randint(0, 100, 20)
array

array([ 4, 42, 58, 31,  1, 65, 41, 57, 35, 11, 46, 82, 91,  0, 14, 99, 53,
       12, 42, 84])

In [57]:
array.dtype

dtype('int64')

### データ型を指定して配列を生成する

In [58]:
array = np.random.randint(0, 100, 20, dtype='int32')
array

array([75, 68,  6, 68, 47,  3, 76, 52, 78, 15, 20, 99, 58, 23, 79, 13, 85,
       48, 49, 69], dtype=int32)

In [59]:
array.dtype

dtype('int32')

### 桁数を丸める

In [60]:
array = np.random.randn(10)
array

array([-0.51080514, -1.18063218, -0.02818223,  0.42833187,  0.06651722,
        0.3024719 , -0.63432209, -0.36274117, -0.67246045, -0.35955316])

In [61]:
np.round(array, 2)

array([-0.51, -1.18, -0.03,  0.43,  0.07,  0.3 , -0.63, -0.36, -0.67,
       -0.36])